#!/usr/bin/env php
<?php

declare(strict_types=1);

use Dotenv\Dotenv;

require __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv::createImmutable(__DIR__, ['.env', '.env.local']);
$dotenv->safeLoad();

defined('YII_DEBUG') or define('YII_DEBUG', (bool) ($_ENV['APP_DEBUG'] ?? false));
defined('YII_ENV')   or define('YII_ENV',   $_ENV['APP_ENV'] ?? 'prod');

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
exit($application->run());
